language: java
env:
  - CACHE_NAME=COMMONS
cache:
  directories: 
    - $HOME/.cache/java/ 
    - $HOME/.m2
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V deploy -s settings.xml
  - mvn sonar:sonar -Dsonar.host.url=http://51.254.133.167:9000 -Dsonar.login=4c2eb3431731550b5ca8ab2610af95f1debe8baf

